### ISSUE TITLE
Progress of your project RamanFlow

### ISSUE THREAD

**Issue by yungyuc** [anva-kn/ramanflow#1]
The repository of your project RamanFlow has not had a lot of code in it and I have not seen testing.  Do you need some discussions or help?

**Comment by anva-kn** [comment]
Dear professor,
Thank you for your email. Indeed I'm a bit behind the schedule. I'm confused about how should I test the fitting, interpolation, and denoising. Because to be honest, I've always tested it by eyes. Maybe you can suggest a good way of testing these things? However, I still have code that I didn't push and that I'm currently working on.

**Comment by yungyuc** [comment]
It is not possible to make concrete suggestions before reading the code.  Please push something and tag me in a new issue for further discussions.
